- name: create ec2 instances
  hosts: localhost
  become: yes
  vars:
    instances: 
    - db
    - backend
    - frontend
  tasks: 
  - name: create ec2 instances
    amazon.aws.ec2_instance:
    instance_type: t2.micro
    image_id: ami-090252cbe067a9e58
    security_group: alloweverything
    name: "{{ item }}"
    tags:
      name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instances_info

- name: print output
  ansible.builtin.debug:
    msg: "output: {{ ec2_instances_info}}"